// Auto-generated by update_dashboard.py  —  2026-06-18T18:14:31
// Live indicators: 28 / 29  |  regime: risk_on  |  composite: 63.5

window.DASHBOARD_DATA = {
  "timestamp": "2026-06-18T18:14:31",
  "spx": {
    "value": 7498.0498046875,
    "change_pct": 1.050520963401445
  },
  "vix_ticker": {
    "value": 16.709999084472656,
    "change_pct": -9.38178633124087
  },
  "vix_contango": {
    "front": true,
    "back": true
  },
  "composite": {
    "full": 63.5,
    "fast": 69.5,
    "regime": "risk_on",
    "weights_used": {
      "cross": 0.13,
      "pos": 0.22,
      "vol": 0.17,
      "credit": 0.28,
      "breadth": 0.2
    },
    "category_scores": {
      "breadth": 58.2,
      "credit": 82.8,
      "cross": 62.7,
      "pos": 43.8,
      "vol": 64.0
    },
    "signal_strength": 0.0,
    "roc": {
      "1w": null,
      "4w": null,
      "range_pct_1y": 100.0
    },
    "window_years": 5
  },
  "indicators": {
    "VIX": {
      "base": 16.709999084472656,
      "pos": 62.05250596658711,
      "z": 0.47652808967538574,
      "freq": "rt"
    },
    "VVIX": {
      "base": 88.91999816894531,
      "pos": 71.09872611464968,
      "z": 0.6719731456661832,
      "freq": "rt"
    },
    "SKEW Index": {
      "base": 142.6199951171875,
      "pos": 45.51440329218107,
      "z": -0.1470843339134395,
      "freq": "daily"
    },
    "VIX Term Structure": {
      "base": 0.873129919327481,
      "pos": 76.05746209098164,
      "z": 0.6751822429025355,
      "freq": "rt"
    },
    "Put/Call Ratio": {
      "base": 0.59,
      "pos": 67.72908366533865,
      "z": 0.5152188970700086,
      "freq": "daily"
    },
    "MOVE Index": {
      "base": 69.36000061035156,
      "pos": 86.96701528559936,
      "z": 1.2611372910983918,
      "freq": "daily"
    },
    "HY Credit Spread": {
      "base": 2.63,
      "pos": 98.22109275730622,
      "z": 1.278696945388163,
      "freq": "daily"
    },
    "IG Credit Spread": {
      "base": 0.92,
      "pos": 99.0,
      "z": 1.263570505357582,
      "freq": "daily"
    },
    "2s10s kurve": {
      "base": 0.29,
      "pos": 56.45669291338583,
      "z": 0.28593134165811235,
      "freq": "daily"
    },
    "Financial Conds.": {
      "base": -0.505,
      "pos": 72.0754716981132,
      "z": 0.6715995001239401,
      "freq": "weekly"
    },
    "SOFR": {
      "base": 3.63,
      "pos": 67.50788643533123,
      "z": -0.07379073500002546,
      "freq": "daily"
    },
    "Guld/S\u00f8lv ratio": {
      "base": 64.2125963278082,
      "pos": 91.25596184419715,
      "z": 1.8353956244219256,
      "freq": "rt"
    },
    "Kobber/Guld ratio": {
      "base": 0.0015049331245612116,
      "pos": 22.17806041335453,
      "z": -0.8918612708253107,
      "freq": "rt"
    },
    "DXY": {
      "base": 100.82499694824219,
      "pos": 58.50556438791733,
      "z": 0.19399912457131144,
      "freq": "rt"
    },
    "XLP / XLY ratio": {
      "base": 0.7120642146785404,
      "pos": 83.35987261146497,
      "z": 1.041305889829218,
      "freq": "rt"
    },
    "Bitcoin (BTC)": {
      "base": 62633.6015625,
      "pos": 58.26944140197152,
      "z": 0.1877702033053766,
      "freq": "rt"
    },
    "NAAIM Exposure": {
      "base": 79.27,
      "pos": 63.051823416506714,
      "z": 0.5084516820549257,
      "freq": "weekly"
    },
    "AAII Bull-Bear": {
      "base": -17.3,
      "pos": 8.91089108910891,
      "z": -1.3813331128966326,
      "freq": "weekly"
    },
    "Investors Intel.": {
      "base": 2.37,
      "pos": 73.6318407960199,
      "z": 0.6617450113926459,
      "freq": "weekly"
    },
    "Short Interest": {
      "base": 2.7,
      "pos": 37.810945273631845,
      "z": -0.2449981597524641,
      "freq": "monthly"
    },
    "Insider Buy/Sell": {
      "base": 0.3,
      "pos": 35.82089552238806,
      "z": -0.3862171603682613,
      "freq": "monthly"
    },
    "% over 50-DMA": {
      "base": 54.87077534791253,
      "pos": 59.523809523809526,
      "z": 0.5362594195520867,
      "freq": "daily"
    },
    "% over 200-DMA": {
      "base": 57.65407554671968,
      "pos": 96.82539682539682,
      "z": 2.0393911943258454,
      "freq": "daily"
    },
    "New Highs - Lows": {
      "base": 4.0,
      "pos": 99.0,
      "z": 15.811513787552672,
      "freq": "daily"
    },
    "A/D Linje": {
      "base": 4182.0,
      "pos": 90.07936507936508,
      "z": 1.2754882404769334,
      "freq": "daily"
    },
    "McClellan Osc.": {
      "base": -0.44673066000794304,
      "pos": 46.42857142857143,
      "z": -0.04856528145524751,
      "freq": "daily"
    },
    "SPY / RSP ratio": {
      "base": 3.5484439551448874,
      "pos": 5.095541401273891,
      "z": -1.6801456638916692,
      "freq": "rt"
    },
    "50/200 DMA divergence": {
      "base": -2.7833001988071544,
      "pos": 10.317460317460316,
      "z": -1.1712032843781546,
      "freq": "daily"
    }
  }
};
