// Auto-generated by update_dashboard.py  —  2026-06-18T13:05:20
// Live indicators: 28 / 29  |  regime: risk_off  |  composite: 60.9

window.DASHBOARD_DATA = {
  "timestamp": "2026-06-18T13:05:20",
  "spx": {
    "value": 7420.10009765625,
    "change_pct": -1.214828210822879
  },
  "vix_ticker": {
    "value": 17.100000381469727,
    "change_pct": -7.266811896848852
  },
  "vix_contango": {
    "front": false,
    "back": true
  },
  "composite": {
    "full": 60.9,
    "fast": 64.7,
    "regime": "risk_off",
    "weights_used": {
      "credit": 0.33,
      "vol": 0.25,
      "pos": 0.18,
      "cross": 0.1,
      "breadth": 0.14
    },
    "category_scores": {
      "breadth": 47.7,
      "credit": 82.0,
      "cross": 62.8,
      "pos": 45.4,
      "vol": 50.8
    },
    "signal_strength": 0.0,
    "roc": {
      "1w": null,
      "4w": null,
      "range_pct_1y": null
    },
    "window_years": 5
  },
  "indicators": {
    "VIX": {
      "base": 17.100000381469727,
      "pos": 57.83611774065235,
      "z": 0.40246343815550134,
      "freq": "rt"
    },
    "VVIX": {
      "base": 94.52999877929688,
      "pos": 55.298804780876495,
      "z": 0.31124552940060773,
      "freq": "rt"
    },
    "SKEW Index": {
      "base": 142.6199951171875,
      "pos": 45.51440329218107,
      "z": -0.1470843339134395,
      "freq": "daily"
    },
    "VIX Term Structure": {
      "base": 0.9762443399861825,
      "pos": 33.22683706070288,
      "z": -0.40545722281168517,
      "freq": "rt"
    },
    "Put/Call Ratio": {
      "base": 0.59,
      "pos": 67.72908366533865,
      "z": 0.5152188970700086,
      "freq": "daily"
    },
    "MOVE Index": {
      "base": 69.36000061035156,
      "pos": 86.96701528559936,
      "z": 1.2611372910983918,
      "freq": "daily"
    },
    "HY Credit Spread": {
      "base": 2.71,
      "pos": 91.73027989821882,
      "z": 1.10785633902841,
      "freq": "daily"
    },
    "IG Credit Spread": {
      "base": 0.93,
      "pos": 97.20101781170483,
      "z": 1.2143157901856403,
      "freq": "daily"
    },
    "2s10s kurve": {
      "base": 0.29,
      "pos": 56.45669291338583,
      "z": 0.28593134165811235,
      "freq": "daily"
    },
    "Financial Conds.": {
      "base": -0.505,
      "pos": 72.0754716981132,
      "z": 0.6715995001239401,
      "freq": "weekly"
    },
    "SOFR": {
      "base": 3.63,
      "pos": 67.50788643533123,
      "z": -0.07379073500002546,
      "freq": "daily"
    },
    "Guld/S\u00f8lv ratio": {
      "base": 64.04028522216183,
      "pos": 91.41494435612083,
      "z": 1.8537212245437653,
      "freq": "rt"
    },
    "Kobber/Guld ratio": {
      "base": 0.0015037787912492268,
      "pos": 22.17806041335453,
      "z": -0.8947758036266478,
      "freq": "rt"
    },
    "DXY": {
      "base": 100.6780014038086,
      "pos": 58.90302066772655,
      "z": 0.2265868609732745,
      "freq": "rt"
    },
    "XLP / XLY ratio": {
      "base": 0.7245649134385092,
      "pos": 80.3187250996016,
      "z": 0.9338493655508772,
      "freq": "rt"
    },
    "Bitcoin (BTC)": {
      "base": 64267.2890625,
      "pos": 61.22672508214677,
      "z": 0.242387241883826,
      "freq": "rt"
    },
    "NAAIM Exposure": {
      "base": 79.27,
      "pos": 63.051823416506714,
      "z": 0.5084516820549257,
      "freq": "weekly"
    },
    "AAII Bull-Bear": {
      "base": -17.3,
      "pos": 8.415841584158416,
      "z": -1.3208834897374364,
      "freq": "weekly"
    },
    "Investors Intel.": {
      "base": 2.37,
      "pos": 81.09452736318407,
      "z": 0.7885106535080145,
      "freq": "weekly"
    },
    "Short Interest": {
      "base": 2.7,
      "pos": 41.29353233830846,
      "z": -0.2657638046468054,
      "freq": "monthly"
    },
    "Insider Buy/Sell": {
      "base": 0.3,
      "pos": 33.33333333333333,
      "z": -0.3338018504739645,
      "freq": "monthly"
    },
    "% over 50-DMA": {
      "base": 53.28031809145129,
      "pos": 55.37848605577689,
      "z": 0.4693893525837262,
      "freq": "daily"
    },
    "% over 200-DMA": {
      "base": 57.45526838966203,
      "pos": 96.41434262948208,
      "z": 2.0517839273700194,
      "freq": "daily"
    },
    "New Highs - Lows": {
      "base": 0.0,
      "pos": 50.0,
      "z": 0.0,
      "freq": "daily"
    },
    "A/D Linje": {
      "base": 4105.0,
      "pos": 85.2589641434263,
      "z": 1.2125614939296259,
      "freq": "daily"
    },
    "McClellan Osc.": {
      "base": -4.62503280717522,
      "pos": 35.85657370517929,
      "z": -0.3312512331623789,
      "freq": "daily"
    },
    "SPY / RSP ratio": {
      "base": 3.54543280777555,
      "pos": 5.338645418326692,
      "z": -1.6714584886908865,
      "freq": "rt"
    },
    "50/200 DMA divergence": {
      "base": -4.174950298210739,
      "pos": 5.9760956175298805,
      "z": -1.2253558652898262,
      "freq": "daily"
    }
  }
};
