// Auto-generated by update_dashboard.py  —  2026-06-28T22:43:24
// Live indicators: 28 / 29  |  regime: risk_off  |  composite: 64.8

window.DASHBOARD_DATA = {
  "timestamp": "2026-06-28T22:43:24",
  "spx": {
    "value": 7354.02001953125,
    "change_pct": -0.047165741757111364
  },
  "vix_ticker": {
    "value": 18.40999984741211,
    "change_pct": -2.541024657202286
  },
  "vix_contango": {
    "front": true,
    "back": true
  },
  "composite": {
    "full": 64.8,
    "fast": 67.2,
    "regime": "risk_off",
    "weights_used": {
      "credit": 0.33,
      "vol": 0.25,
      "cross": 0.1,
      "breadth": 0.14,
      "pos": 0.18
    },
    "category_scores": {
      "breadth": 75.3,
      "credit": 82.8,
      "cross": 59.5,
      "pos": 55.2,
      "vol": 44.2
    },
    "signal_strength": 0.0,
    "roc": {
      "1w": 1.9,
      "4w": null,
      "cache_days": 11,
      "range_pct_1y": 66.7
    },
    "window_years": 5
  },
  "indicators": {
    "VIX": {
      "base": 18.40999984741211,
      "pos": 46.09872611464968,
      "z": 0.15467709092551207,
      "freq": "rt",
      "date": "2026-06-26"
    },
    "VVIX": {
      "base": 89.0199966430664,
      "pos": 70.59760956175299,
      "z": 0.6606902580838263,
      "freq": "rt",
      "date": "2026-06-26"
    },
    "SKEW Index": {
      "base": 139.39999389648438,
      "pos": 56.95473251028807,
      "z": 0.0889816327264632,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "VIX Term Structure": {
      "base": 0.9125474946390139,
      "pos": 59.44223107569721,
      "z": 0.267875739795618,
      "freq": "rt",
      "date": "2026-06-26"
    },
    "Put/Call Ratio": {
      "base": 0.85,
      "pos": 2.1484375,
      "z": -2.133696457728515,
      "freq": "daily",
      "date": "2026-06-28"
    },
    "MOVE Index": {
      "base": 66.79000091552734,
      "pos": 89.88764044943821,
      "z": 1.3667431949699549,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "HY Credit Spread": {
      "base": 2.78,
      "pos": 84.24396442185514,
      "z": 0.9439457271218299,
      "freq": "daily",
      "date": "2026-06-25"
    },
    "IG Credit Spread": {
      "base": 0.95,
      "pos": 92.88437102922491,
      "z": 1.1035043249773722,
      "freq": "daily",
      "date": "2026-06-25"
    },
    "2s10s kurve": {
      "base": 0.31,
      "pos": 57.96529968454258,
      "z": 0.3371631041268573,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "Financial Conds.": {
      "base": -0.516,
      "pos": 76.51515151515152,
      "z": 0.7540038515192999,
      "freq": "weekly",
      "date": "2026-06-19"
    },
    "SOFR": {
      "base": 3.64,
      "pos": 66.56126482213438,
      "z": -0.06789566409676677,
      "freq": "daily",
      "date": "2026-06-25"
    },
    "Guld/S\u00f8lv ratio": {
      "base": 68.96505224621336,
      "pos": 88.79173290937997,
      "z": 1.3269775839925686,
      "freq": "rt",
      "date": "2026-06-28"
    },
    "Kobber/Guld ratio": {
      "base": 0.001520320039615932,
      "pos": 23.211446740858506,
      "z": -0.8444124826929271,
      "freq": "rt",
      "date": "2026-06-28"
    },
    "DXY": {
      "base": 101.37899780273438,
      "pos": 56.04133545310016,
      "z": 0.08206877605265019,
      "freq": "rt",
      "date": "2026-06-28"
    },
    "XLP / XLY ratio": {
      "base": 0.7406662328422846,
      "pos": 76.09561752988049,
      "z": 0.7906009400633895,
      "freq": "rt",
      "date": "2026-06-26"
    },
    "Bitcoin (BTC)": {
      "base": 59070.23828125,
      "pos": 53.420908593322395,
      "z": 0.06343649981705822,
      "freq": "rt",
      "date": "2026-06-28"
    },
    "NAAIM Exposure": {
      "base": 98.59,
      "pos": 95.01915708812261,
      "z": 1.3226749883187794,
      "freq": "weekly",
      "date": "2026-06-24"
    },
    "AAII Bull-Bear": {
      "base": -2.8,
      "pos": 32.51231527093596,
      "z": -0.41904166629442313,
      "freq": "weekly",
      "date": "2026-06-21"
    },
    "Investors Intel.": {
      "base": 2.37,
      "pos": 81.09452736318407,
      "z": 0.8862899707700667,
      "freq": "weekly",
      "date": "2026-06-21"
    },
    "Short Interest": {
      "base": 2.7,
      "pos": 35.3233830845771,
      "z": -0.3232681992336718,
      "freq": "monthly",
      "date": "2026-06-21"
    },
    "Insider Buy/Sell": {
      "base": 0.3,
      "pos": 31.8407960199005,
      "z": -0.4630772430520337,
      "freq": "monthly",
      "date": "2026-06-21"
    },
    "% over 50-DMA": {
      "base": 64.01590457256461,
      "pos": 88.84462151394422,
      "z": 0.9237512060795303,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "% over 200-DMA": {
      "base": 63.02186878727635,
      "pos": 99.0,
      "z": 2.238256576273148,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "New Highs - Lows": {
      "base": 0.0,
      "pos": 99.0,
      "z": 0.0,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "A/D Linje": {
      "base": 3887.0,
      "pos": 99.0,
      "z": 1.6629525994089658,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "McClellan Osc.": {
      "base": 17.070996271056313,
      "pos": 90.83665338645417,
      "z": 1.2225869778911163,
      "freq": "daily",
      "date": "2026-06-26"
    },
    "SPY / RSP ratio": {
      "base": 3.4662640801527926,
      "pos": 12.031872509960166,
      "z": -1.3593071297129715,
      "freq": "rt",
      "date": "2026-06-26"
    },
    "50/200 DMA divergence": {
      "base": 0.9940357852882613,
      "pos": 38.24701195219124,
      "z": -1.0614983798283386,
      "freq": "daily",
      "date": "2026-06-26"
    }
  }
};
